import globals from 'globals'
import pluginJs from '@eslint/js'
import tseslint from 'typescript-eslint'
import pluginReactConfig from 'eslint-plugin-react/configs/recommended.js'
import eslintConfigLove from 'eslint-config-love'
import stylistic from '@stylistic/eslint-plugin'

export default [
  {
    ignores: [
      '**/build/**',
      '**/coverage/**',
      '**/dist/**',
      '**/node_modules/**',
      'eslint.config.mjs',
      'vitest.config.ts',
    ],
  },
  {
    plugins: {
      '@stylistic': stylistic,
    },
    ...stylistic.configs.recommended,
  },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    files: ['**/*.jsx', '**/*.js', '**/*.ts', '**/*.tsx'],
    ...eslintConfigLove,
  },
  {
    files: ['**/*.jsx', '**/*.js', '**/*.ts', '**/*.tsx'],
    ...pluginReactConfig,
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
        projectService: true,
      },
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      '@stylistic/jsx-one-expression-per-line': 'off',
      '@stylistic/array-bracket-newline': ['error', { multiline: true }],
      '@stylistic/array-element-newline': ['error', { consistent: true, multiline: true }],
      '@stylistic/arrow-spacing': ['error', { before: true, after: true }],
      '@stylistic/block-spacing': ['error', 'always'],
      '@stylistic/brace-style': ['error', '1tbs', { allowSingleLine: true }],
      '@stylistic/eol-last': ['error', 'always'],
      '@stylistic/jsx-quotes': ['error', 'prefer-single'],
      '@stylistic/jsx-wrap-multilines': ['error', {
        declaration: 'parens-new-line',
        assignment: 'parens-new-line',
        return: 'parens-new-line',
        arrow: 'parens-new-line',
        condition: 'parens-new-line',
        logical: 'parens-new-line',
        prop: 'parens-new-line',
        propertyValue: 'parens-new-line',
      }],
      '@stylistic/key-spacing': ['error', { beforeColon: false, afterColon: true }],
      '@stylistic/keyword-spacing': ['error', { before: true, after: true }],
      '@stylistic/max-statements-per-line': ['error', { max: 2 }],
      '@stylistic/member-delimiter-style': ['error', {
        multiline: { delimiter: 'none' },
        singleline: { delimiter: 'comma' },
      }],
      '@stylistic/no-trailing-spaces': 'error',
      '@stylistic/object-curly-newline': ['error', { consistent: true, multiline: true }],
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
      '@stylistic/operator-linebreak': ['error', 'before', { overrides: { '=': 'after' } }],
      '@stylistic/quote-props': ['error', 'as-needed', { keywords: false, unnecessary: true, numbers: true }],
      '@stylistic/quotes': ['error', 'single'],
      '@stylistic/semi': ['error', 'never'],
      '@stylistic/space-before-blocks': ['error', 'always'],
      '@stylistic/space-before-function-paren': ['error', 'always'],
      '@stylistic/space-infix-ops': ['error', { int32Hint: false }],
      '@stylistic/type-annotation-spacing': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'separate-type-imports' }],
      '@typescript-eslint/init-declarations': 'off',
      '@typescript-eslint/max-params': ['error', { max: 3 }],
      '@typescript-eslint/no-magic-numbers': 'off',
      '@typescript-eslint/no-misused-spread': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-parameters': 'off',
      '@typescript-eslint/no-unsafe-type-assertion': 'off',
      '@typescript-eslint/non-nullable-type-assertion-style': 'off',
      '@typescript-eslint/prefer-destructuring': 'off',
      '@typescript-eslint/switch-exhaustiveness-check': 'off',
      'arrow-body-style': 'off',
      complexity: 'off',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'eslint-comments/require-description': 'off',
      'max-lines': 'off',
      'max-nested-callbacks': ['error', 5],
      'no-await-in-loop': 'off',
      'no-console': 'warn',
      'no-misused-spread': 'off',
      'no-multi-spaces': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0 }],
      'no-negated-condition': 'off',
      'no-param-reassign': 'off',
      'no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      }],
      'preserve-caught-error': ['error', { requireCatchParameter: true }],
      'promise/avoid-new': 'off',
      radix: ['error', 'as-needed'],
      'react/function-component-definition': ['error', {
        namedComponents: 'function-declaration',
        unnamedComponents: 'arrow-function',
      }],
      'react/jsx-curly-spacing': ['error', { when: 'never', children: true }],
      'react/jsx-first-prop-new-line': ['error', 'multiline'],
      'react/jsx-tag-spacing': ['error', { beforeSelfClosing: 'always', beforeClosing: 'never' }],
      'react/jsx-wrap-multilines': ['error', { prop: 'parens-new-line' }],
      'react/react-in-jsx-scope': 'off',
      'react/self-closing-comp': ['error', { html: true, component: true }],
    },
  },
  {
    files: ['**/__tests__/**/*'],
    rules: {
      '@typescript-eslint/max-params': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/strict-void-return': 'off',
      'max-nested-callbacks': 'off',
      'no-console': 'off',
      'prefer-arrow-callback': 'off',
    },
  },
]
